### ISSUE TITLE
Payment through RFID

### ISSUE THREAD

**Issue by Icety** [AreaFiftyLAN/lancie-api#269]
Make the user able to pay with their RFID wristband.
This should implement:
- [ ] Prices for consumptions
- [ ] Credit for a user
- [ ] Credit toevoegen: third product type

**Comment by skamoen** [comment]
Awesome, but too risky. What to do with leftovers and such. WIth the mobile pinjetser we pretty much solve this
